site_name: METAKINA RWA课程学习平台
site_url: https://您的GitHub用户名.github.io/您的仓库名称/
site_description: 免费的RWA(Real World Assets)课程学习平台，提供全面的实物资产代币化知识
site_author: METAKINA

# GitHub Pages 部署配置
repo_url: https://github.com/您的GitHub用户名/您的仓库名称
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  language: zh
  custom_dir: overrides
  logo: assets/images/metakina_logo.png
  favicon: assets/images/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # 亮色模式配置
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换至深色模式
    # 深色模式配置
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换至亮色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.tracking
    - navigation.top
    - toc.follow
    - toc.integrate
    - content.tabs.link
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    - search.highlight
    - search.share
    - search.suggest

extra_javascript:
  - assets/js/custom.js

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - 首页: index.md
  - 课程模块:
    - 课程概述: courses/overview.md
    - 模块一：RWA基础: courses/module1.md
    - 模块二：区块链与RWA: courses/module2.md
    - 模块三：RWA投资策略: courses/module3.md
    - 模块四：RWA实践案例: courses/module4.md
    - 模块五：合规生命线: courses/module5.md
    - 模块六：走向市场: courses/module6.md
    - 模块七：行业深潜: courses/module7.md
    - 模块八：慧眼识珠: courses/module8.md
    - 模块九：预见未来: courses/module9.md
  - 资源中心: resources.md
  - 关于METAKINA: about.md